grep -c "AAAA	TTTT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "AAAA	TTAA	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "AAAA	AATT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "AAAA	GGTT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "AAAA	TTGG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "AAAA	CCTT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "AAAA	TTCC	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "AAAA	ATAT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "AAAA	TATA	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "AAAA	GTGT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "AAAA	TGTG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "AAAA	CTCT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "AAAA	TCTC	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "AAAA	CACA	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "AAAA	ACAC	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "AAAA	GAGA	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "AAAA	AGAG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "AAAA	CGCG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "AAAA	GCGC	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "AAAA	ATGC	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "AAAA	TAGC	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "AAAA	GCTA	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "AAAA	GCAT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "AAAA	TACG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "AAAA	ATCG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "AAAA	CGTA	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "AAAA	CGAT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "AAAA	CTAG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "AAAA	TCAG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "AAAA	AGCT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "AATT	TTTT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "AATT	TTAA	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "AATT	AATT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "AATT	GGTT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "AATT	TTGG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "AATT	CCTT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "AATT	TTCC	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "AATT	ATAT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "AATT	TATA	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "AATT	GTGT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "AATT	TGTG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "AATT	CTCT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "AATT	TCTC	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "AATT	CACA	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "AATT	ACAC	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "AATT	GAGA	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "AATT	AGAG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "AATT	CGCG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "AATT	GCGC	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "AATT	ATGC	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "AATT	TAGC	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "AATT	GCTA	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "AATT	GCAT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "AATT	TACG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "AATT	ATCG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "AATT	CGTA	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "AATT	CGAT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "AATT	CTAG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "AATT	TCAG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "AATT	AGCT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "TTAA	TTTT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "TTAA	TTAA	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "TTAA	AATT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "TTAA	GGTT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "TTAA	TTGG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "TTAA	CCTT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "TTAA	TTCC	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "TTAA	ATAT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "TTAA	TATA	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "TTAA	GTGT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "TTAA	TGTG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "TTAA	CTCT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "TTAA	TCTC	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "TTAA	CACA	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "TTAA	ACAC	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "TTAA	GAGA	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "TTAA	AGAG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "TTAA	CGCG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "TTAA	GCGC	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "TTAA	ATGC	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "TTAA	TAGC	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "TTAA	GCTA	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "TTAA	GCAT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "TTAA	TACG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "TTAA	ATCG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "TTAA	CGTA	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "TTAA	CGAT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "TTAA	CTAG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "TTAA	TCAG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "TTAA	AGCT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "AACC	TTTT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "AACC	TTAA	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "AACC	AATT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "AACC	GGTT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "AACC	TTGG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "AACC	CCTT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "AACC	TTCC	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "AACC	ATAT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "AACC	TATA	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "AACC	GTGT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "AACC	TGTG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "AACC	CTCT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "AACC	TCTC	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "AACC	CACA	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "AACC	ACAC	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "AACC	GAGA	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "AACC	AGAG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "AACC	CGCG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "AACC	GCGC	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "AACC	ATGC	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "AACC	TAGC	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "AACC	GCTA	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "AACC	GCAT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "AACC	TACG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "AACC	ATCG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "AACC	CGTA	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "AACC	CGAT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "AACC	CTAG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "AACC	TCAG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "AACC	AGCT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CCAA	TTTT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CCAA	TTAA	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CCAA	AATT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CCAA	GGTT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CCAA	TTGG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CCAA	CCTT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CCAA	TTCC	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CCAA	ATAT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CCAA	TATA	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CCAA	GTGT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CCAA	TGTG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CCAA	CTCT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CCAA	TCTC	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CCAA	CACA	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CCAA	ACAC	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CCAA	GAGA	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CCAA	AGAG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CCAA	CGCG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CCAA	GCGC	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CCAA	ATGC	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CCAA	TAGC	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CCAA	GCTA	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CCAA	GCAT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CCAA	TACG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CCAA	ATCG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CCAA	CGTA	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CCAA	CGAT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CCAA	CTAG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CCAA	TCAG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CCAA	AGCT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "AAGG	TTTT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "AAGG	TTAA	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "AAGG	AATT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "AAGG	GGTT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "AAGG	TTGG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "AAGG	CCTT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "AAGG	TTCC	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "AAGG	ATAT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "AAGG	TATA	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "AAGG	GTGT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "AAGG	TGTG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "AAGG	CTCT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "AAGG	TCTC	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "AAGG	CACA	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "AAGG	ACAC	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "AAGG	GAGA	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "AAGG	AGAG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "AAGG	CGCG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "AAGG	GCGC	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "AAGG	ATGC	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "AAGG	TAGC	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "AAGG	GCTA	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "AAGG	GCAT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "AAGG	TACG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "AAGG	ATCG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "AAGG	CGTA	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "AAGG	CGAT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "AAGG	CTAG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "AAGG	TCAG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "AAGG	AGCT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "GGAA	TTTT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "GGAA	TTAA	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "GGAA	AATT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "GGAA	GGTT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "GGAA	TTGG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "GGAA	CCTT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "GGAA	TTCC	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "GGAA	ATAT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "GGAA	TATA	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "GGAA	GTGT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "GGAA	TGTG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "GGAA	CTCT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "GGAA	TCTC	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "GGAA	CACA	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "GGAA	ACAC	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "GGAA	GAGA	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "GGAA	AGAG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "GGAA	CGCG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "GGAA	GCGC	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "GGAA	ATGC	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "GGAA	TAGC	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "GGAA	GCTA	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "GGAA	GCAT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "GGAA	TACG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "GGAA	ATCG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "GGAA	CGTA	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "GGAA	CGAT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "GGAA	CTAG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "GGAA	TCAG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "GGAA	AGCT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "ATAT	TTTT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "ATAT	TTAA	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "ATAT	AATT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "ATAT	GGTT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "ATAT	TTGG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "ATAT	CCTT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "ATAT	TTCC	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "ATAT	ATAT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "ATAT	TATA	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "ATAT	GTGT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "ATAT	TGTG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "ATAT	CTCT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "ATAT	TCTC	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "ATAT	CACA	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "ATAT	ACAC	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "ATAT	GAGA	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "ATAT	AGAG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "ATAT	CGCG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "ATAT	GCGC	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "ATAT	ATGC	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "ATAT	TAGC	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "ATAT	GCTA	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "ATAT	GCAT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "ATAT	TACG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "ATAT	ATCG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "ATAT	CGTA	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "ATAT	CGAT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "ATAT	CTAG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "ATAT	TCAG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "ATAT	AGCT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "TATA	TTTT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "TATA	TTAA	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "TATA	AATT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "TATA	GGTT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "TATA	TTGG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "TATA	CCTT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "TATA	TTCC	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "TATA	ATAT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "TATA	TATA	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "TATA	GTGT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "TATA	TGTG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "TATA	CTCT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "TATA	TCTC	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "TATA	CACA	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "TATA	ACAC	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "TATA	GAGA	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "TATA	AGAG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "TATA	CGCG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "TATA	GCGC	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "TATA	ATGC	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "TATA	TAGC	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "TATA	GCTA	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "TATA	GCAT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "TATA	TACG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "TATA	ATCG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "TATA	CGTA	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "TATA	CGAT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "TATA	CTAG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "TATA	TCAG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "TATA	AGCT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "ACAC	TTTT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "ACAC	TTAA	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "ACAC	AATT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "ACAC	GGTT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "ACAC	TTGG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "ACAC	CCTT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "ACAC	TTCC	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "ACAC	ATAT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "ACAC	TATA	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "ACAC	GTGT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "ACAC	TGTG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "ACAC	CTCT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "ACAC	TCTC	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "ACAC	CACA	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "ACAC	ACAC	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "ACAC	GAGA	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "ACAC	AGAG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "ACAC	CGCG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "ACAC	GCGC	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "ACAC	ATGC	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "ACAC	TAGC	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "ACAC	GCTA	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "ACAC	GCAT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "ACAC	TACG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "ACAC	ATCG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "ACAC	CGTA	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "ACAC	CGAT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "ACAC	CTAG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "ACAC	TCAG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "ACAC	AGCT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CACA	TTTT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CACA	TTAA	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CACA	AATT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CACA	GGTT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CACA	TTGG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CACA	CCTT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CACA	TTCC	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CACA	ATAT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CACA	TATA	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CACA	GTGT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CACA	TGTG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CACA	CTCT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CACA	TCTC	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CACA	CACA	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CACA	ACAC	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CACA	GAGA	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CACA	AGAG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CACA	CGCG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CACA	GCGC	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CACA	ATGC	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CACA	TAGC	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CACA	GCTA	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CACA	GCAT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CACA	TACG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CACA	ATCG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CACA	CGTA	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CACA	CGAT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CACA	CTAG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CACA	TCAG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CACA	AGCT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "AGAG	TTTT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "AGAG	TTAA	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "AGAG	AATT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "AGAG	GGTT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "AGAG	TTGG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "AGAG	CCTT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "AGAG	TTCC	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "AGAG	ATAT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "AGAG	TATA	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "AGAG	GTGT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "AGAG	TGTG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "AGAG	CTCT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "AGAG	TCTC	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "AGAG	CACA	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "AGAG	ACAC	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "AGAG	GAGA	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "AGAG	AGAG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "AGAG	CGCG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "AGAG	GCGC	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "AGAG	ATGC	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "AGAG	TAGC	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "AGAG	GCTA	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "AGAG	GCAT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "AGAG	TACG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "AGAG	ATCG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "AGAG	CGTA	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "AGAG	CGAT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "AGAG	CTAG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "AGAG	TCAG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "AGAG	AGCT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "GAGA	TTTT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "GAGA	TTAA	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "GAGA	AATT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "GAGA	GGTT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "GAGA	TTGG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "GAGA	CCTT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "GAGA	TTCC	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "GAGA	ATAT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "GAGA	TATA	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "GAGA	GTGT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "GAGA	TGTG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "GAGA	CTCT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "GAGA	TCTC	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "GAGA	CACA	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "GAGA	ACAC	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "GAGA	GAGA	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "GAGA	AGAG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "GAGA	CGCG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "GAGA	GCGC	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "GAGA	ATGC	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "GAGA	TAGC	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "GAGA	GCTA	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "GAGA	GCAT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "GAGA	TACG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "GAGA	ATCG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "GAGA	CGTA	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "GAGA	CGAT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "GAGA	CTAG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "GAGA	TCAG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "GAGA	AGCT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "TGTG	TTTT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "TGTG	TTAA	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "TGTG	AATT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "TGTG	GGTT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "TGTG	TTGG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "TGTG	CCTT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "TGTG	TTCC	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "TGTG	ATAT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "TGTG	TATA	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "TGTG	GTGT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "TGTG	TGTG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "TGTG	CTCT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "TGTG	TCTC	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "TGTG	CACA	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "TGTG	ACAC	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "TGTG	GAGA	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "TGTG	AGAG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "TGTG	CGCG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "TGTG	GCGC	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "TGTG	ATGC	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "TGTG	TAGC	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "TGTG	GCTA	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "TGTG	GCAT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "TGTG	TACG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "TGTG	ATCG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "TGTG	CGTA	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "TGTG	CGAT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "TGTG	CTAG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "TGTG	TCAG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "TGTG	AGCT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "GTGT	TTTT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "GTGT	TTAA	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "GTGT	AATT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "GTGT	GGTT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "GTGT	TTGG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "GTGT	CCTT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "GTGT	TTCC	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "GTGT	ATAT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "GTGT	TATA	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "GTGT	GTGT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "GTGT	TGTG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "GTGT	CTCT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "GTGT	TCTC	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "GTGT	CACA	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "GTGT	ACAC	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "GTGT	GAGA	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "GTGT	AGAG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "GTGT	CGCG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "GTGT	GCGC	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "GTGT	ATGC	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "GTGT	TAGC	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "GTGT	GCTA	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "GTGT	GCAT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "GTGT	TACG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "GTGT	ATCG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "GTGT	CGTA	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "GTGT	CGAT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "GTGT	CTAG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "GTGT	TCAG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "GTGT	AGCT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "TCTC	TTTT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "TCTC	TTAA	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "TCTC	AATT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "TCTC	GGTT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "TCTC	TTGG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "TCTC	CCTT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "TCTC	TTCC	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "TCTC	ATAT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "TCTC	TATA	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "TCTC	GTGT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "TCTC	TGTG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "TCTC	CTCT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "TCTC	TCTC	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "TCTC	CACA	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "TCTC	ACAC	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "TCTC	GAGA	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "TCTC	AGAG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "TCTC	CGCG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "TCTC	GCGC	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "TCTC	ATGC	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "TCTC	TAGC	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "TCTC	GCTA	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "TCTC	GCAT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "TCTC	TACG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "TCTC	ATCG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "TCTC	CGTA	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "TCTC	CGAT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "TCTC	CTAG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "TCTC	TCAG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "TCTC	AGCT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CTCT	TTTT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CTCT	TTAA	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CTCT	AATT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CTCT	GGTT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CTCT	TTGG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CTCT	CCTT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CTCT	TTCC	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CTCT	ATAT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CTCT	TATA	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CTCT	GTGT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CTCT	TGTG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CTCT	CTCT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CTCT	TCTC	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CTCT	CACA	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CTCT	ACAC	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CTCT	GAGA	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CTCT	AGAG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CTCT	CGCG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CTCT	GCGC	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CTCT	ATGC	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CTCT	TAGC	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CTCT	GCTA	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CTCT	GCAT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CTCT	TACG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CTCT	ATCG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CTCT	CGTA	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CTCT	CGAT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CTCT	CTAG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CTCT	TCAG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CTCT	AGCT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CGCG	TTTT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CGCG	TTAA	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CGCG	AATT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CGCG	GGTT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CGCG	TTGG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CGCG	CCTT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CGCG	TTCC	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CGCG	ATAT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CGCG	TATA	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CGCG	GTGT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CGCG	TGTG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CGCG	CTCT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CGCG	TCTC	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CGCG	CACA	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CGCG	ACAC	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CGCG	GAGA	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CGCG	AGAG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CGCG	CGCG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CGCG	GCGC	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CGCG	ATGC	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CGCG	TAGC	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CGCG	GCTA	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CGCG	GCAT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CGCG	TACG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CGCG	ATCG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CGCG	CGTA	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CGCG	CGAT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CGCG	CTAG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CGCG	TCAG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CGCG	AGCT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "GCGC	TTTT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "GCGC	TTAA	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "GCGC	AATT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "GCGC	GGTT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "GCGC	TTGG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "GCGC	CCTT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "GCGC	TTCC	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "GCGC	ATAT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "GCGC	TATA	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "GCGC	GTGT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "GCGC	TGTG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "GCGC	CTCT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "GCGC	TCTC	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "GCGC	CACA	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "GCGC	ACAC	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "GCGC	GAGA	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "GCGC	AGAG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "GCGC	CGCG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "GCGC	GCGC	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "GCGC	ATGC	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "GCGC	TAGC	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "GCGC	GCTA	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "GCGC	GCAT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "GCGC	TACG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "GCGC	ATCG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "GCGC	CGTA	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "GCGC	CGAT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "GCGC	CTAG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "GCGC	TCAG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "GCGC	AGCT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "GCAT	TTTT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "GCAT	TTAA	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "GCAT	AATT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "GCAT	GGTT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "GCAT	TTGG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "GCAT	CCTT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "GCAT	TTCC	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "GCAT	ATAT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "GCAT	TATA	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "GCAT	GTGT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "GCAT	TGTG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "GCAT	CTCT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "GCAT	TCTC	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "GCAT	CACA	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "GCAT	ACAC	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "GCAT	GAGA	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "GCAT	AGAG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "GCAT	CGCG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "GCAT	GCGC	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "GCAT	ATGC	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "GCAT	TAGC	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "GCAT	GCTA	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "GCAT	GCAT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "GCAT	TACG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "GCAT	ATCG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "GCAT	CGTA	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "GCAT	CGAT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "GCAT	CTAG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "GCAT	TCAG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "GCAT	AGCT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "GCTA	TTTT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "GCTA	TTAA	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "GCTA	AATT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "GCTA	GGTT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "GCTA	TTGG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "GCTA	CCTT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "GCTA	TTCC	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "GCTA	ATAT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "GCTA	TATA	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "GCTA	GTGT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "GCTA	TGTG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "GCTA	CTCT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "GCTA	TCTC	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "GCTA	CACA	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "GCTA	ACAC	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "GCTA	GAGA	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "GCTA	AGAG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "GCTA	CGCG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "GCTA	GCGC	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "GCTA	ATGC	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "GCTA	TAGC	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "GCTA	GCTA	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "GCTA	GCAT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "GCTA	TACG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "GCTA	ATCG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "GCTA	CGTA	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "GCTA	CGAT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "GCTA	CTAG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "GCTA	TCAG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "GCTA	AGCT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "TAGC	TTTT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "TAGC	TTAA	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "TAGC	AATT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "TAGC	GGTT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "TAGC	TTGG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "TAGC	CCTT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "TAGC	TTCC	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "TAGC	ATAT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "TAGC	TATA	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "TAGC	GTGT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "TAGC	TGTG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "TAGC	CTCT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "TAGC	TCTC	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "TAGC	CACA	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "TAGC	ACAC	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "TAGC	GAGA	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "TAGC	AGAG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "TAGC	CGCG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "TAGC	GCGC	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "TAGC	ATGC	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "TAGC	TAGC	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "TAGC	GCTA	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "TAGC	GCAT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "TAGC	TACG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "TAGC	ATCG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "TAGC	CGTA	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "TAGC	CGAT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "TAGC	CTAG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "TAGC	TCAG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "TAGC	AGCT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "ATGC	TTTT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "ATGC	TTAA	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "ATGC	AATT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "ATGC	GGTT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "ATGC	TTGG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "ATGC	CCTT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "ATGC	TTCC	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "ATGC	ATAT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "ATGC	TATA	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "ATGC	GTGT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "ATGC	TGTG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "ATGC	CTCT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "ATGC	TCTC	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "ATGC	CACA	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "ATGC	ACAC	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "ATGC	GAGA	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "ATGC	AGAG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "ATGC	CGCG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "ATGC	GCGC	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "ATGC	ATGC	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "ATGC	TAGC	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "ATGC	GCTA	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "ATGC	GCAT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "ATGC	TACG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "ATGC	ATCG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "ATGC	CGTA	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "ATGC	CGAT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "ATGC	CTAG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "ATGC	TCAG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "ATGC	AGCT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CGTA	TTTT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CGTA	TTAA	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CGTA	AATT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CGTA	GGTT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CGTA	TTGG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CGTA	CCTT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CGTA	TTCC	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CGTA	ATAT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CGTA	TATA	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CGTA	GTGT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CGTA	TGTG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CGTA	CTCT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CGTA	TCTC	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CGTA	CACA	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CGTA	ACAC	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CGTA	GAGA	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CGTA	AGAG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CGTA	CGCG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CGTA	GCGC	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CGTA	ATGC	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CGTA	TAGC	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CGTA	GCTA	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CGTA	GCAT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CGTA	TACG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CGTA	ATCG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CGTA	CGTA	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CGTA	CGAT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CGTA	CTAG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CGTA	TCAG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CGTA	AGCT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CGAT	TTTT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CGAT	TTAA	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CGAT	AATT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CGAT	GGTT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CGAT	TTGG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CGAT	CCTT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CGAT	TTCC	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CGAT	ATAT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CGAT	TATA	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CGAT	GTGT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CGAT	TGTG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CGAT	CTCT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CGAT	TCTC	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CGAT	CACA	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CGAT	ACAC	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CGAT	GAGA	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CGAT	AGAG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CGAT	CGCG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CGAT	GCGC	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CGAT	ATGC	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CGAT	TAGC	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CGAT	GCTA	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CGAT	GCAT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CGAT	TACG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CGAT	ATCG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CGAT	CGTA	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CGAT	CGAT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CGAT	CTAG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CGAT	TCAG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CGAT	AGCT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "TACG	TTTT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "TACG	TTAA	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "TACG	AATT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "TACG	GGTT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "TACG	TTGG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "TACG	CCTT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "TACG	TTCC	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "TACG	ATAT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "TACG	TATA	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "TACG	GTGT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "TACG	TGTG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "TACG	CTCT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "TACG	TCTC	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "TACG	CACA	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "TACG	ACAC	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "TACG	GAGA	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "TACG	AGAG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "TACG	CGCG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "TACG	GCGC	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "TACG	ATGC	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "TACG	TAGC	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "TACG	GCTA	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "TACG	GCAT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "TACG	TACG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "TACG	ATCG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "TACG	CGTA	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "TACG	CGAT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "TACG	CTAG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "TACG	TCAG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "TACG	AGCT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "ATCG	TTTT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "ATCG	TTAA	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "ATCG	AATT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "ATCG	GGTT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "ATCG	TTGG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "ATCG	CCTT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "ATCG	TTCC	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "ATCG	ATAT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "ATCG	TATA	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "ATCG	GTGT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "ATCG	TGTG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "ATCG	CTCT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "ATCG	TCTC	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "ATCG	CACA	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "ATCG	ACAC	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "ATCG	GAGA	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "ATCG	AGAG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "ATCG	CGCG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "ATCG	GCGC	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "ATCG	ATGC	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "ATCG	TAGC	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "ATCG	GCTA	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "ATCG	GCAT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "ATCG	TACG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "ATCG	ATCG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "ATCG	CGTA	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "ATCG	CGAT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "ATCG	CTAG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "ATCG	TCAG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "ATCG	AGCT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CTAG	TTTT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CTAG	TTAA	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CTAG	AATT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CTAG	GGTT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CTAG	TTGG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CTAG	CCTT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CTAG	TTCC	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CTAG	ATAT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CTAG	TATA	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CTAG	GTGT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CTAG	TGTG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CTAG	CTCT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CTAG	TCTC	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CTAG	CACA	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CTAG	ACAC	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CTAG	GAGA	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CTAG	AGAG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CTAG	CGCG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CTAG	GCGC	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CTAG	ATGC	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CTAG	TAGC	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CTAG	GCTA	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CTAG	GCAT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CTAG	TACG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CTAG	ATCG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CTAG	CGTA	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CTAG	CGAT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CTAG	CTAG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CTAG	TCAG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CTAG	AGCT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CTGA	TTTT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CTGA	TTAA	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CTGA	AATT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CTGA	GGTT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CTGA	TTGG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CTGA	CCTT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CTGA	TTCC	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CTGA	ATAT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CTGA	TATA	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CTGA	GTGT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CTGA	TGTG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CTGA	CTCT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CTGA	TCTC	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CTGA	CACA	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CTGA	ACAC	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CTGA	GAGA	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CTGA	AGAG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CTGA	CGCG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CTGA	GCGC	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CTGA	ATGC	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CTGA	TAGC	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CTGA	GCTA	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CTGA	GCAT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CTGA	TACG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CTGA	ATCG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CTGA	CGTA	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CTGA	CGAT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CTGA	CTAG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CTGA	TCAG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "CTGA	AGCT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "AGCT	TTTT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "AGCT	TTAA	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "AGCT	AATT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "AGCT	GGTT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "AGCT	TTGG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "AGCT	CCTT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "AGCT	TTCC	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "AGCT	ATAT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "AGCT	TATA	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "AGCT	GTGT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "AGCT	TGTG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "AGCT	CTCT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "AGCT	TCTC	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "AGCT	CACA	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "AGCT	ACAC	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "AGCT	GAGA	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "AGCT	AGAG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "AGCT	CGCG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "AGCT	GCGC	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "AGCT	ATGC	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "AGCT	TAGC	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "AGCT	GCTA	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "AGCT	GCAT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "AGCT	TACG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "AGCT	ATCG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "AGCT	CGTA	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "AGCT	CGAT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "AGCT	CTAG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "AGCT	TCAG	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
grep -c "AGCT	AGCT	" All_with_F_and_R_and_2_barcodes_and_grthn265_minus_lsthn_5_pct_type1_only.fa
